name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest tests

  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/halalina-service:prod .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/halalina-service:prod

  deploy:
    name: Pull and Run on VPS (Prod)
    runs-on: self-hosted
    needs: build

    steps:
      - name: Stop and Remove Old Container
        run: |
          docker stop halalina-service-prod || true
          docker rm halalina-service-prod || true

      - name: Pull Latest Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/halalina-service:prod

      - name: Run New Container
        run: |
          docker run -d \
            --name halalina-service-prod \
            -p 5003:5002 \
            --env-file ~/halalina-service/.env.prod \
            --network halalina-prod-network \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/halalina-service:prod
